version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - path: ./postgresql/.env
        required: true
    ports:
      - "5432:5432"
    network_mode: host
    volumes:
      - ./postgresql:/var/lib/postgresql

