version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - path: ./postgresql/.env
        required: true
    ports:
      - "5432:5432"
    network_mode: host
    volumes:
      - ./postgresql:/var/lib/postgresql

  backend:
    build: ./backend
    image: backend
    container_name: backend
    ports:
      - "8000:8000"
    restart: always
    network_mode: host
    env_file:
      - path: ./backend/.env
        required: true
    depends_on:
      - db
