"""SearchTerm and SearchRsults table

Revision ID: 6b01d4ad7343
Revises: 
Create Date: 2024-03-19 13:25:32.063824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b01d4ad7343'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_terms_id'), 'search_terms', ['id'], unique=False)
    op.create_index(op.f('ix_search_terms_term'), 'search_terms', ['term'], unique=False)
    op.create_table('search_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('result_id', sa.String(), nullable=True),
    sa.Column('result_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['term_id'], ['search_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_results_id'), 'search_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_results_id'), table_name='search_results')
    op.drop_table('search_results')
    op.drop_index(op.f('ix_search_terms_term'), table_name='search_terms')
    op.drop_index(op.f('ix_search_terms_id'), table_name='search_terms')
    op.drop_table('search_terms')
    # ### end Alembic commands ###
